services:
    ai-rest:
        build:
            context: './ai-rest'
            dockerfile: Dockerfile
        volumes:
        - ./ai-rest/api:/app
        ports:
        - "5000:5000"
        networks:
        - ozawa
    # frontend:
    #     build:
    #         context: './frontend'
    #         dockerfile: Dockerfile
    #     volumes:
    #     - ./frontend:/app
    #     ports:
    #     - "5500:5500"
    #     networks:
    #     - ozawa
networks:
    ozawa:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
